logging:
  level:
    org:
      apache: WARN
      codehaus.groovy: WARN
      elasticsearch: WARN
      flywaydb: WARN
      glassfish: TRACE
      hibernate: WARN
      springframework: WARN
      springframework.boot: WARN
      springframework.boot.context.embedded.tomcat: INFO
      springframework.cache: TRACE
      springframework.cloud: TRACE
    gex.jaxrs: DEBUG
    gex.serling.pub: DEBUG
    gex.serling.pub.restv1.providers: DEBUG
    grails: WARN



server:
  port: 9191
  tomcat:
    # Write access log to target/logs/access_log.YYYY-MM-DD.log
    # See http://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/valves/AccessLogValve.html
    accessLogEnabled: true
    #accessLogPattern: '%a %l %u %t "%r" %s %b %{Host}i %{Location}o'
    accessLogPattern: combined
    baseDir: '..'
    backgroundProcessorDelay: 1

management:
  port: 9192
  context-path: /management
  security.enabled: false
